### ISSUE TITLE
Permit another port than 3306

### ISSUE THREAD

**Issue by cyberbobjr** [emilioastarita/typed-rows#1]
Hi,
some MySQL server don't use the default port 3306 (like MAMP), it will be nice if we can choose the port of MySQL server instead of using the default port.
Many thanks for your nice tool !
Regards

**Comment by cyberbobjr** [comment]
Ok i don't have the rights for a PR, so i created a fork with the options params, you can check here 
https://github.com/cyberbobjr/typed-rows.git

**Comment by emilioastarita** [comment]
Hello @cyberbobjr could you please send the PR to this repo?

**Comment by cyberbobjr** [comment]
Hello,
i tried this afternoon, but i don't have rights on it :/

**Comment by emilioastarita** [comment]
I'm not sure why you aren't able to PR to this repo. I did the PR manually from you fork and I've already merged. Thanks!
