### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by bigteejay** [emilioastarita/typed-rows#5]
Running from global install in Win 7, 64bit...

> (node:6232) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
> C:\Users\some.user\AppData\Roaming\npm\node_modules\typed-rows\node_modules\mysql\lib\protocol\Parser.js:80
>         throw err; // Rethrow non-MySQL errors
>         ^
> 
> TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
>     at maybeCallback (fs.js:140:9)
>     at Object.fs.write (fs.js:656:14)
>     at C:\Users\some.user\AppData\Roaming\npm\node_modules\typed-rows\js\TypedRows.js:61:24
>     at C:\Users\some.user\AppData\Roaming\npm\node_modules\typed-rows\node_modules\async\dist\async.js:1126:9
>     at C:\Users\some.user\AppData\Roaming\npm\node_modules\typed-rows\node_modules\async\dist\async.js:473:16
>     at iteratorCallback (C:\Users\some.user\AppData\Roaming\npm\node_modules\typed-rows\node_modules\async\dist\async.js:1050:13)
>     at C:\Users\some.user\AppData\Roaming\npm\node_modules\typed-rows\node_modules\async\dist\async.js:958:16
>     at C:\Users\some.user\AppData\Roaming\npm\node_modules\typed-rows\node_modules\async\dist\async.js:1123:13
>     at Query._callback (C:\Users\some.user\AppData\Roaming\npm\node_modules\typed-rows\js\TypedRows.js:57:25)
>     at Query.Sequence.end (C:\Users\some.user\AppData\Roaming\npm\node_modules\typed-rows\node_modules\mysql\lib\protocol\sequences\Sequence.js:88:24)

```
node -v
v10.1.0
```

```
npm -v
6.0.0
```

```
ver
Microsoft Windows [Version 6.1.7601]
```

**Comment by emilioastarita** [comment]
Could you please test again with latest released version (0.2.3) ? 
thx!
